[project]
name = "hydrator"
authors = [
    { name = "Paul Durivage", email = "durivage@google.com" },
    { name = "Kevin Park", email = "kevinpmwpark@google.com" },
]
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
version = "2.1.0"
dependencies = [
    "aiofiles>=24.1.0,<25",
    "aioshutil>=1.5,<2",
    "jinja2>=3.1.6,<4",
    "pyyaml>=6.0.2,<7",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pylint>=3.3.8",
    "types-aiofiles>=24.1.0.20250822",
    "types-pyyaml>=6.0.12.20250915",
]

[project.scripts]
hydrate = "hydrator.__main__:main"
hydrator = "hydrator.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["src"]
