on:
  pull_request:
    branches:
      - main

name: test app

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: install dependencies
        run: uv sync --all-extras --verbose
      
      - name: pylint
        run: uv run pylint --fail-on=E src/
      
      - name: mypy
        run: uv run mypy src/
      
      - name: test hydrator sync
        run: uv run -m unittest -vv tests/test_cluster_cli.py
      
      - name: test hydrator async
        run: uv run -m unittest -vv tests/test_cluster_async.py
