on:
  pull_request:
    branches:
      - main

name: test app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: install dependencies
        run: pip3 install -r requirements-dev.txt --require-hashes
      - name: install hydrator
        run: pip install .[dev]
      - name: pylint
        run: pylint --fail-on=E src/
      - name: mypy
        run: mypy src/
      - name: test hydrator sync
        run: python3 -m unittest -vv tests/test_cluster_cli.py
      - name: test hydrator async
        run: python3 -m unittest -vv tests/test_cluster_async.py
